<?php get_header(); ?>

<section class="content-section container">
	<h2> About </h2>
	<p>
			Have the central idea in your mind and convey it right at the beginning. A lot of times the central idea is conveyed right in the first sentence. “Oceans are slowly becoming human dust-bins.” Once the statement of your main idea is out there, you will be explaining or providing validation points.<img class="about-band-image" src="wp-content/themes/test-site/images/image.jpg"> This way, your main idea isn’t hanging loose. This is going to make sure how the reader is going to interpret the main idea, because of you leading them to it. This is where the writer explains the focus point. “Garbage in the ocean comes from trash from trash cans, the streets, and landfills that gets blown into sewers, rivers, or directly into the ocean. The trash makes its way into storm drains. Trash travels through sewer pipes, into waterways, and finally into the ocean.” Use an Example Examples always clarify without explanations. People understand better when you give them something to relate to. They provide the necessary evidence or support required to prove our central idea. “A new study – based on what researchers called a mega-expedition to the Great Pacific Garbage Patch in 2015 – suggests there is about 16 times more waste than previously thought floating there. The mass of waste spans 617,763 square miles(1.6 million square km), about three times the size of France.”
		</p>
		<p>
			Have the central idea in your mind and convey it right at the beginning. A lot of times the central idea is conveyed right in the first sentence. “Oceans are slowly becoming human dust-bins.” Once the statement of your main idea is out there, you will be explaining or providing validation points. This way, your main idea isn’t hanging loose. This is going to make sure how the reader is going to interpret the main idea, because of you leading them to it. This is where the writer explains the focus point. “Garbage in the ocean comes from trash from trash cans, the streets, and landfills that gets blown into sewers, rivers, or directly into the ocean. The trash makes its way into storm drains. Trash travels through sewer pipes, into waterways, and finally into the ocean.” Use an Example Examples always clarify without explanations. People understand better when you give them something to relate to. They provide the necessary evidence or support required to prove our central idea. “A new study – based on what researchers called a mega-expedition to the Great Pacific Garbage Patch in 2015 – suggests there is about 16 times more waste than previously thought floating there. The mass of waste spans 617,763 square miles(1.6 million square km), about three times the size of France.”
		</p>
</section>

<?php get_footer(); ?>